#version: 2.1
#
#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test


version: 2.1
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:11-stretch-node
    steps:
      - checkout
      - run: mvn package

workflows:
  version: 2
  build:
    jobs:
      - test